### PR TITLE
BUGFIX: Fixes incorrect metric symbol when on mobile

### LINKED ISSUE #2274: Regression: pct_rate showing as 100k
**Describe the bug**

Women in gov should show as a pct not a 100k

This should have been fixed in #2239

Ideally we should add a playwright test to prevent this from regressing in the future 

image

### PR DESCRIPTION
**Pull request by eriwarr**
## Description

- Moves function to `mapHelpers.ts` file. 
- Adds `chartIsSmall && !usePercentSuffix` logic back to the previously removed function in the last PR. 
- Adds Playwright tests for the `createBarLabel` function. 

## Motivation and Context

Fixes #2274

## Has this been tested? How?
Playwright tests have been written to ensure the correct strings are generated.  

## Screenshots (if appropriate):
_Bug_
Screenshot 2023-07-12 at 11 01 54 AM

_Fix_

## Types of changes
- Bug fix
Screenshot 2023-07-12 at 11 02 57 AM

## Post-merge TODO
I have inspected frontend changes and run affected data pipelines:
- [ ] on DEV
- [ ] on PROD

## Preview link below in Netlify comment 😎

### CODE REVIEW

File: frontend/src/charts/SimpleHorizontalBarChart.tsx [hunk 1]
```diff
@@ -59,16 +56,7 @@ function getSpec(
...
-  "${usePercentSuffix ? SINGLE_LINE_PERCENT : measure === 'hiv_stigma_index' ? '' : PER_100K}"`
-
-  const multiLine100kLabel = `[datum.${tooltipMetricDisplayColumnName}, "${PER_100K}"]`
-
-  const createBarLabel = () => {
-    if (chartIsSmall) {
-      return multiLine100kLabel
-    } else return singleLineLabel
-  }
+  const barLabel = createBarLabel(chartIsSmall, measure, tooltipMetricDisplayColumnName, usePercentSuffix)
```
Comment (benhammondmusic) [inline frontend/src/charts/SimpleHorizontalBarChart.tsx:59]: nice

**Review by benhammondmusic — APPROVED** [review]
awesome. thanks for adding the tests as well
