### PR TITLE
Legend fix

### LINKED ISSUE #2144: Vega legend has incorrect ranges on state and county-level data
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Device (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by eriwarr**
## Description
This PR includes a fix for the incorrectly displayed ranges in the legend and losing the choropleth map on state-level views with county-level data 

- Shows a summary data point on the legend when viewing county-level data or when county-level data is unavailable on the state-level view (_used a separate legend marker to achieve this_).
- Removed the `CountyUnavailableAlert` (_info can now be seen on the legend_). 
- Added HIV metrics to the topics that need a '0' legend marker.
- Updated logic to properly split up the buckets where ranges are very small (_still using quantile_). 
- Adds the 'Note' indicator to the card.
- Updates the `allowsBreakdowns` function to accept a list of metric IDs (_HIV deaths data does not have county-level data, so we'll only return state and national responses from the HIV provider file_). 

## Motivation and Context

- Fixes #2144 _(see screenshots on this issue)_
- The map card does not display the map when there is no county-level data on the state view (_, i.e., HIV deaths_).

## Has this been tested? How?
It was tested locally.

## Screenshots (if appropriate):
_Summary data point used when no county-level data available_
Screenshot 2023-04-26 at 10 06 36 AM

_Summary data point used when viewing county-level data_
Screenshot 2023-04-26 at 10 08 50 AM

_Legend appropriately splits buckets when the range is small_
Screenshot 2023-04-26 at 10 25 54 AM

## Types of changes
- Bug fix

## Post-merge TODO
I have inspected frontend changes and run affected data pipelines:
- [ ] on DEV
- [ ] on PROD

## Preview link below in Netlify comment 😎

### CODE REVIEW

File: frontend/src/charts/ChoroplethMap.tsx [hunk 1]
```diff
@@ -251,7 +254,8 @@ export function ChoroplethMap(props: ChoroplethMapProps) {
     const helperLegend = getHelperLegend(
       /* yOffset */ yOffsetNoDataLegend,
       /* xOffset */ xOffsetNoDataLegend,
-      /* overrideGrayMissingWithZeroYellow */ isCawp && !props.listExpanded
+      /* overrideGrayMissingWithZeroYellow */(isCawpOrHiv) &&
```
Comment (benhammondmusic) [inline frontend/src/charts/ChoroplethMap.tsx:257]: can we use something like `containsZeros` instead of making it variable based? That'll allow us to expand further as more topics come in that might have zeros we want to have a unique color

File: frontend/src/charts/Legend.tsx [hunk 2]
```diff
@@ -43,10 +48,18 @@ export interface LegendProps {
...
+  hasSelfButNotChildGeoData?: boolean
 }
 
 export function Legend(props: LegendProps) {
   const isCawp = CAWP_DETERMINANTS.includes(props.metric.metricId)
+  const isHiv = HIV_DETERMINANTS.includes(props.metric.metricId)
+  const isCawpOrHiv = isCawp || isHiv
+
+  const legendColorCount =
+    props.legendData && props.legendData.length < 6
```
Comment (benhammondmusic) [inline frontend/src/charts/Legend.tsx:60]: can we use the global instead of hard coding in `6`

File: frontend/src/data/config/MetricConfig.ts [hunk 3]
```diff
@@ -633,7 +633,7 @@ export const METRIC_CONFIG: Record<DropdownVarId, VariableConfig[]> = {
           type: 'pct_share',
         },
         pct_relative_inequity: {
-          chartTitleLines: ['Historical data linkage to HIV care inequity'],
+          chartTitleLines: ['Historical data for linkage to HIV care inequity'],
```
Comment (benhammondmusic) [inline frontend/src/data/config/MetricConfig.ts:636]: how about `Historical inequities in linkage to HIV care` ?

File: frontend/src/data/variables/VariableProvider.ts [hunk 4]
```diff
@@ -141,7 +141,10 @@ abstract class VariableProvider {
     metricQuery: MetricQuery
   ): Promise<MetricQueryResponse>
 
-  abstract allowsBreakdowns(breakdowns: Breakdowns): boolean
+  abstract allowsBreakdowns(
+    breakdowns: Breakdowns,
+    metricIds?: MetricId[]
+  ): boolean
```
Comment (benhammondmusic) [inline frontend/src/data/variables/VariableProvider.ts:147]: nice work

File: frontend/src/cards/ShareTrendsChartCard.tsx [hunk 5]
```diff
@@ -228,12 +228,11 @@ export function ShareTrendsChartCard(props: ShareTrendsChartCardProps) {
...
                 <Alert severity="info" role="note">
-                  This chart graph visualizes the disproportionate share of
+                  This chart graph visualizes the disproportionate share of{' '}
                   {props.variableConfig.variableFullDisplayName} as experienced
-                  by different races and/or ethnic group(s) compared to their
-                  relative share of the population (when we default to showing
-                  only the highest and lowest historical averages). Read more
-                  about this calculation in our{' '}
+                  by different demographic group(s) compared to their relative
+                  share of the population. Read more about this calculation in
```
Comment (benhammondmusic) [inline frontend/src/cards/ShareTrendsChartCard.tsx:234]: can this be `by different demographic groups compared to their relative shares`? specifically leave out the optional plural and pluralize `share`? I think in almost all cases this chart will show multiple groups so we don't need to use optional plurals

**Review by benhammondmusic — APPROVED** [review]
