### PR TITLE
Fix for `0 rendering in the unknowns alert`

### LINKED ISSUE #1612: `0` rendering in the unknowns alert
**Describe the bug**

In the unknowns alert right after the demograhpic breakdown type, a `0` is rendering. This is likely some logic that is returning `false` but being cast as a string `"0"`

**To Reproduce**
1. Go to [this HET report](https://healthequitytracker.org/exploredata?mls=1.covid-3.39003&demo=race_and_ethnicity&dt1=covid_hospitalizations)
2. scroll down to the last card "Age Adusted"
3. observe the first alert

**Screenshots**

Screen Shot 2022-06-01 at 1 30 34 PM

**Expected behavior**
no `0`

### PR DESCRIPTION
**Pull request by eriwarr**
## Preview Link

<a href="https://deploy-preview-1619--health-equity-tracker.netlify.app/" target="_blank">
  <br />
Click to demo updates </a>   <-- Update this link once you have PR# 

## Description

-Fixes #1612 
Fixed the rendering of `0` when there are no secondary age percentages to display.  React skips rendering for anything that is (`typeof boolean` or `undefined`) and will render anything that is (`typeof string` or `number`). Updated the logic to the use of a ternary expression; which will only render the percentage when we have one to display. 

## Screenshots (if appropriate):
Screen Shot 2022-06-06 at 11 13 49 AM

Screen Shot 2022-06-06 at 11 14 29 AM

## Types of changes

- Bug fix

### CODE REVIEW

File: frontend/src/cards/ui/UnknownsAlert.tsx [hunk 1]
```diff
@@ -130,8 +130,9 @@ function UnknownsAlert(props: UnknownsAlertProps) {
             ? RACE_OR_ETHNICITY
             : breakdownVarDisplayName}
           {/* Age Adjusted Card reports both unknown RACE + AGE */}
-          {secondaryAgePercentageUnknown &&
-            `, and ${secondaryAgePercentageUnknown}${props.metricConfig.shortLabel} reported an unknown age`}
+          {secondaryAgePercentageUnknown
+            ? `, and ${secondaryAgePercentageUnknown}${props.metricConfig.shortLabel} reported an unknown age`
+            : null}
```
Comment (benhammondmusic) [inline frontend/src/cards/ui/UnknownsAlert.tsx:135]: sweet. Ya We've run into this a couple times; i tend to default to the short circuit operators `&&` but we DEF can't use those in these conditional text blocks. Thanks for the quick fix!!

**Review by benhammondmusic — APPROVED** [review]
awesome dude! Now I can go make some more bugs 🐛
