### PR TITLE
Fix NaNs in highest/lowest

### LINKED ISSUE #927: deaths and hosps for Covid show NaN on top 5 dropdown
on national map

### PR DESCRIPTION
**Pull request by vanshkumar**
Closes #927

### CODE REVIEW

**Review by joshzarrabi — APPROVED** [review]

File: frontend/src/data/utils/datasetutils.ts [hunk 1]
```diff
@@ -146,6 +146,7 @@ export const getLowestN = (
   listSize: number
 ): Row[] => {
   return data
+    .filter((row: Row) => !isNaN(row[fieldName]) && row[fieldName] !== null)
```
Comment (aaronsn) [inline frontend/src/data/utils/datasetutils.ts:149]: Is it possible the data has undefined in it? You can use `!=` instead of `!==` to capture both null and undefined

Comment (vanshkumar) [reply frontend/src/data/utils/datasetutils.ts:149]: It is possible, did not know that you could do that, done!
