### PR TITLE
Fixes issues with linking to specific page sections

### LINKED ISSUE #1192: internal anchor links not always working
links such as `healthequitytracker.org/exploredata#missingDataInfo` aren't functioning properly. This is due React Router. The internal link is handled by a `scrollIntoView()` function; we need to implement a useEffect on pages that might receive `#jump-to-section` links and intercept that hash and execute the scroll into view.

### PR DESCRIPTION
**Pull request by benhammondmusic**
fixes #1192

due to React Router it's not always possible to simply link to a page section using `<a href="page#specificSection">`; this PR fixes problematic links by intercepting the `#specificSection` and executing a scroll into view command, or simply passing the function with ref in scope down via props to the sending component button. I have tested all links throughout the site and they all are working, but further ongoing testing should be done in other browsers.

We also should consider #1263

### CODE REVIEW

File: frontend/src/cards/ui/HighestLowestList.tsx [hunk 1]
```diff
@@ -104,8 +106,13 @@ export function HighestLowestList(props: HighestLowestListProps) {
       <p>All rates are reported as: {props.metricConfig.fullCardTitleName}</p>
       <p>
         Consider the possible impact of{" "}
-        <a href="#missingDataInfo">data reporting gaps</a> when interpreting the
-        highest and lowest rates.
+        <Button
+          onClick={() => props.jumpToData!()}
```
Comment (benhammondmusic) [inline frontend/src/cards/ui/HighestLowestList.tsx:110]: Maybe better to account for situations where the jumpTo method hasn’t been passed; or require it as a prop?

File: frontend/src/pages/DataCatalog/MethodologyTab.tsx [hunk 2]
```diff
@@ -120,9 +121,9 @@ function MethodologyTab() {
                 <p>
                   For a description of some of the gaps in COVID-19 data, please
                   see the{" "}
-                  <a href={EXPLORE_DATA_PAGE_WHAT_DATA_ARE_MISSING_LINK}>
+                  <Link to={EXPLORE_DATA_PAGE_WHAT_DATA_ARE_MISSING_LINK}>
```
Comment (joshzarrabi) [inline frontend/src/pages/DataCatalog/MethodologyTab.tsx:124]: This one didn't work for me, it brought me to the middle of the exploredata page

**Review by joshzarrabi — CHANGES_REQUESTED** [review]

File: frontend/src/pages/DataCatalog/MethodologyTab.tsx (hunk 2 above)
Comment (benhammondmusic) [reply frontend/src/pages/DataCatalog/MethodologyTab.tsx:124]: weird, it's broken for me now; was working before. I wondered why we are linking back to this section at all, I made another issue for this but to make i feel like the INFO should live on the methodology and the DATA should live on the tracker...

**Review by joshzarrabi — APPROVED** [review]
Very fancy, lets look into not linking back to the tracker in a later issue.

File: frontend/src/pages/DataCatalog/MethodologyTab.tsx (hunk 2 above)
Comment (benhammondmusic) [reply frontend/src/pages/DataCatalog/MethodologyTab.tsx:124]: Implemented some min heights for the cards; that should be in place anyways because cumulative layout shift is a) really annoying to the user and b) penalized by Google ranking. By adding min heights to the objects that take a while to load you can minimuze how much the page shifts around. This seems to have fixed / helped a lot with letting the link scroll to the info section properly

**Comment by benhammondmusic** [comment]
Adding min heights to the cards bumped desktop lighthouse from a 35 to a 40; reducing CLS from 0.477 to 0.277

And it seems to fix the inaccurate link-to-section scrolling

before
after
