### PR TITLE
FRONTEND: Display select AHR conditions as `pct_rate` not `per_100k`

### LINKED ISSUE #2210: Alignment of territory circles/labels is off for multimap view
**Describe the bug**
The postal labels should be directly beneath the circles, as they are on the regular map view

**To Reproduce**
1. Click "view multiple maps" when on a national report

**Screenshots**

Screen Shot 2023-05-16 at 11 45 51 AM

### PR DESCRIPTION
**Pull request by benhammondmusic**
## Description

switches AhrProvider to read in and display the new `_pct_rate` rather than the old `_per_100k` for 
- [x] voting
- [x] avoided care

Also
- fixes display issues with Population vs Distribution card title
- linting, sorting MetricIds alphabetically
- [x] checked condition definitions for pct/100k
- [x] updated methodology 
- [x] fixes incorrect definition of voter participation (now it's only presidential)
- [x] fixes responsive / multimap layout issues / legend stuff
- [x] simplify OneVar and TwoVar card rendering
- [x] handle `pct_rate` properly not as a pretend 100k in metric_config 
- [x] fixes missing trigger for topic-specific missing data blurbs on HIV, PREP and AHR
- [x] properly hides time-series cards for BJS reports (but shows for Vera) 

## Motivation and Context

frontend for #2195 
fixes #2210 

## Has this been tested? How?

visually

## Screenshots (if appropriate):

MULTIMAP
Screen Shot 2023-05-17 at 1 34 53 PM
Screen Shot 2023-05-17 at 1 35 23 PM

% not 100k
Screen Shot 2023-05-17 at 2 12 42 PM
Screen Shot 2023-05-17 at 2 12 54 PM
Screen Shot 2023-05-17 at 2 13 06 PM

MISSING DATA 
Screen Shot 2023-05-17 at 2 13 24 PM

Uses correct title for pop. v distr. card; shows title even when chart isn't available
Screen Shot 2023-05-12 at 9 55 44 PM

## Types of changes
- Bug fix
- New content or feature
- Refactor / chore

## Post-merge TODO
I have inspected frontend changes and/or run affected data pipelines:
- [ ] on DEV
- [ ] on PROD

## Preview link below in Netlify comment 😎

### CODE REVIEW

File: frontend/src/data/config/MetricConfig.ts [hunk 1]
```diff
@@ -55,169 +55,169 @@ export type VariableId =
   | 'svi'
 
 export type MetricId =
```
Comment (eriwarr) [inline frontend/src/data/config/MetricConfig.ts:57]: Thanks for ordering this!

**Review by eriwarr — APPROVED** [review]
🚀
