### PR TITLE
Fix for data table title

### LINKED ISSUE #2130: Location not dynamic on table title
**Describe the bug**
Every report says United States

**Expected behavior**

Should reflect the actual FIPS being reported

**Screenshots**

image

### PR DESCRIPTION
**Pull request by eriwarr**
## Description
This PR fixes the data table title issue where the title only displays the location of the United States.

- Refactors the condition in the sentenceCaseName function to ensure that 'hiv_care' is not included in the if clause of the ternary operator.
- Adds the `getSentenceDisplayName()` to the `TableChart.tsx` file.

## Motivation and Context

Fixes #2130

## Has this been tested? How?
Tested locally

## Screenshots (if appropriate):

- Before: Screenshot 2023-04-17 at 3 41 02 PM
- After: Screenshot 2023-04-17 at 3 40 31 PM

## Types of changes
- Bug fix

## Post-merge TODO
I have inspected frontend changes and/or run affected data pipelines:
- [ ] on DEV
- [ ] on PROD

## Preview link below in Netlify comment 😎

### CODE REVIEW

File: frontend/src/charts/TableChart.tsx [hunk 1]
```diff
@@ -173,7 +175,16 @@ export function TableChart(props: TableChartProps) {
     paddingBottom: 10,
   }
 
-  const sentenceCaseName = ['hiv', 'covid', 'copd'].some((substring) =>
+  const metricSubstrings = [
```
Comment (benhammondmusic) [inline frontend/src/charts/TableChart.tsx:178]: maybe we should consider having two properties on the MetricConfig, one a string for at the front of a sentence and one for use in the middle of the sentence? It feels weird to do all this string manipulation just to get it to capitalize properly, but it's fine for now. Maybe when we tackle re-organizing the metric config

File: frontend/src/charts/TableChart.tsx [hunk 2]
```diff
@@ -173,7 +175,16 @@ export function TableChart(props: TableChartProps) {
...
+    'hiv_diagnoses',
+    'hiv_deaths',
+    'hiv_prep',
+    'hiv_prevalence',
+    'covid',
+    'copd',
+  ]
+
+  const sentenceCaseName = metricSubstrings.some((substring) =>
```
Comment (benhammondmusic) [inline frontend/src/charts/TableChart.tsx:187]: I would prefer sending in the typed VariableConfig as a prop, and then rather then searching for a sub string, we could trigger not lowercasing the first letter if  `VARIABLE_IDS_NEEDING_UPPERCASE.includes(props.variableConfig.variableId)`

Just in general a lot cleaner to do conditional off of complete id matches versus seeking substrings since we never know what strings these values might change to in the future

File: frontend/src/charts/TableChart.tsx [hunk 3]
```diff
@@ -186,7 +197,8 @@ export function TableChart(props: TableChartProps) {
       ) : (
         <figure>
           <figcaption style={titleStyle}>
-            Data breakdown summary for {sentenceCaseName} in the United States
+            Data breakdown summary for {sentenceCaseName} in{' '}
```
Comment (benhammondmusic) [inline frontend/src/charts/TableChart.tsx:200]: do you think we need data here? Maybe just `Breakdown summary for ...` works fine? Any chance we get to shorten our text and labels I think we should take it

**Review by benhammondmusic — APPROVED** [review]
