### PR TITLE
FRONTEND: Highest/Lowest fix

### LINKED ISSUE #1958: Highest/Lowest averages button only showing highest group
**Describe the bug**

Clicking the highest/lowest groups button should activate 2 groups on the RateTrends card

**To Reproduce**
1. Go to https://healthequitytracker.org/exploredata?mls=1.covid-3.44&dt1=covid_cases#rates-over-time
2. Click "Show highest lowest averages" button
3. Only "highest" hispanic is shown

**Expected behavior**

A second line, showing the lowest group should be shown, and the corresponding swatch should be activated in the legend

**Screenshots**

Screen Shot 2023-01-10 at 1 36 31 PM

### PR DESCRIPTION
**Pull request by eriwarr**
## Description

- Removes the null values(ALL) from the highest/lowest list. 

## Motivation and Context

Fixes #1958

## Has this been tested? How?
It has been tested locally. 

## Screenshots (if appropriate):
_Bug_
Screenshot 2023-07-06 at 4 41 52 PM

_Fix_
Screenshot 2023-07-06 at 4 40 10 PM

## Types of changes
- Bug fix

## Post-merge TODO
I have inspected frontend changes and/or run affected data pipelines:
- [ ] on DEV
- [ ] on PROD

## Preview link below in Netlify comment 😎

### CODE REVIEW

File: frontend/src/data/utils/DatasetTimeUtils.ts [hunk 1]
```diff
@@ -246,16 +246,20 @@ export function getMinMaxGroups(data: TrendsData): DemographicGroup[] {
     )
 
     const nonNullGroupValues = nonNullGroupData.map((dataPoint) => dataPoint[1])
+
     const sumOfGroupValues = nonNullGroupValues.reduce((a, b) => a + b, 0)
     const numberOfGroupValues = nonNullGroupValues.length
     const groupAverage =
       Math.round((sumOfGroupValues / numberOfGroupValues) * 10) / 10
+      console.log({groupAverage})
```
Comment (benhammondmusic) [inline frontend/src/data/utils/DatasetTimeUtils.ts:254]: Remove this?

File: frontend/src/data/utils/DatasetTimeUtils.ts [hunk 2]
```diff
@@ -246,16 +246,20 @@ export function getMinMaxGroups(data: TrendsData): DemographicGroup[] {
...
+
     return [groupData[0], groupAverage]
   })
 
+
   const values: number[] = groupAveragesOverTime.map(
     (row: any) => row[1] as number
-  )
+  ).filter((value) => value !== null)
```
Comment (benhammondmusic) [inline frontend/src/data/utils/DatasetTimeUtils.ts:262]: Should we use != instead of !== to also filter out undefined values?

**Review by benhammondmusic — APPROVED** [review]
Awesome thanks so much !!
